

development:
  adapter: postgresql
  encoding: unicode
  database: <%= KEYS[:database]["dev_database"] %>
  pool: 5
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: <%= KEYS[:database]["test_database"] %>
  pool: 5
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: <%= KEYS[:database]["production_database"] %>
  host: conpass.space
  pool: 5
  username: <%= KEYS[:database]["db_user"] %>
  password: <%= KEYS[:database]["password"] %>